# Machine-readable licensing declaration, following the REUSE 3.3
# specification of the Free Software Foundation Europe
# (https://reuse.software/spec-3.3/).
#
# The repository has a single licence, CC BY 4.0, covering every file: the text
# of the specification, the fillable templates and the interaction-capture
# script. This file adds no second licence: it makes the same declaration
# readable file by file by an automated tool, which is the form the European
# reuse ecosystem expects.

version = 1

SPDX-PackageName = "memento-ai-docs"
SPDX-PackageSupplier = "Ufficio Servizi per la Transizione al Digitale, Università degli Studi di Urbino Carlo Bo <ufficio.transizionedigitale@uniurb.it>"
SPDX-PackageDownloadLocation = "https://github.com/uniurbit/memento-ai-docs"

[[annotations]]
path = "**"
precedence = "closest"
SPDX-FileCopyrightText = "2026 Università degli Studi di Urbino Carlo Bo"
SPDX-License-Identifier = "CC-BY-4.0"
